name: Tests

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: [ '10', '11', '12', '13', '14' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install Dependencies
        run: yarn

      - name: Run tests
        run: yarn test --ci