name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
        check-latest: true
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
