name: Tests

on:
  push:
    branches:
      - develop
      - develop-new

jobs:
  test:
    strategy:
      matrix:
        node: ['12', '14']
        platform: ['ubuntu-latest', macos-latest]

    runs-on: ${{ matrix.platform }}

    name: Node ${{ matrix.node }} ${{ matrix.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test:cov --ci

      - name: Run e2e tests
        run: yarn test:e2e --ci