name: Tests

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: ['10', '12', '14']
        platform: ['ubuntu-latest', macos-latest]

    runs-on: ${{ matrix.platform }}

    name: Node ${{ matrix.node }} ${{ matrix.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn

      - name: Run tests
        run: yarn test --ci --coverage